# Generated by Django 6.0.5 on 2026-07-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=30)),
                ('author', models.CharField(default=None, max_length=30)),
                ('review', models.CharField(default=None, max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
