# Generated by Django 6.0.5 on 2026-07-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bookmodel',
            name='review',
        ),
        migrations.RemoveField(
            model_name='bookmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='book_author',
            field=models.CharField(default=' ', max_length=30),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='book_short_review',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='book_title',
            field=models.CharField(default=' ', max_length=30),
        ),
    ]
